
{{- if not .Values.wyze.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wyze-bridge.fullname" . }}
  labels:
    {{- include "wyze-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  wyze-username: {{ .Values.wyze.username | b64enc | quote }}
  wyze-password: {{ .Values.wyze.password | b64enc | quote }}
{{- end }}