entrypoints: []
routes:
  - routeMatch: ""
    middlewares: []
    #  - name: ""
    #    namespace: ""
    service:
      name: ""
      port: ""
      kind: ""

tls: 
  commonName: ""
  hosts: []
  issuerRef:
    name: ""
    kind: ""


